# Generated by Django 3.0.7 on 2020-06-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=' ')),
                ('voiceNote', models.TextField(max_length=150)),
                ('qrImage', models.ImageField(upload_to='')),
                ('noOfScans', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.Place')),
            ],
        ),
    ]
