# Generated by Django 3.0.7 on 2020-06-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('altr1', models.CharField(max_length=100)),
                ('image2', models.ImageField(upload_to='')),
                ('altr2', models.CharField(max_length=100)),
                ('image3', models.ImageField(upload_to='')),
                ('altr3', models.CharField(max_length=100)),
                ('image4', models.ImageField(upload_to='')),
                ('altr4', models.CharField(max_length=100)),
                ('image5', models.ImageField(upload_to='')),
                ('altr5', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.Item')),
            ],
        ),
    ]
